"""Typed Python API for the CRC Framework computation core."""

from .constants import HORIZONS, PATHWAYS, RISK_FACTORS, Pathway, RiskFactor
from .distributions import (
    Distribution,
    EmpiricalDistribution,
    FitConstraints,
    FitDiagnostics,
    FitResult,
    FittedDistribution,
    HurdleDistribution,
    HurdleQuantileFitDiagnostics,
    HurdleQuantileFitResult,
    PointMassDistribution,
    QuantileFitDiagnostics,
    QuantileFitResult,
    TabulatedDistribution,
    fit_all,
    fit_distribution,
    fit_hurdle_quantiles,
    fit_quantiles,
    quality_metrics,
)
from .metrics import (
    BinaryOutcome,
    Microscore,
    MicroscoreSuite,
    RiskResult,
    compute_risk,
    compute_spanning_set,
    generate_microscores,
)
from .models import Geography, ScenarioMetadata, TransformContext
from .spatial import lookup_continent, lookup_geography, lookup_ipcc_region
from .transforms import (
    CallableImpact,
    CallableTransform,
    ClimateImpact,
    ImpactFunction,
    ImpactRegistry,
    LinearImpact,
    PiecewiseLinearImpact,
    SigmoidImpact,
    impacts,
)

__all__ = [
    "HORIZONS",
    "PATHWAYS",
    "RISK_FACTORS",
    "BinaryOutcome",
    "CallableImpact",
    "CallableTransform",
    "ClimateImpact",
    "Distribution",
    "EmpiricalDistribution",
    "FitConstraints",
    "FitDiagnostics",
    "FitResult",
    "FittedDistribution",
    "Geography",
    "HurdleDistribution",
    "HurdleQuantileFitDiagnostics",
    "HurdleQuantileFitResult",
    "ImpactFunction",
    "ImpactRegistry",
    "LinearImpact",
    "Microscore",
    "MicroscoreSuite",
    "Pathway",
    "PiecewiseLinearImpact",
    "PointMassDistribution",
    "QuantileFitDiagnostics",
    "QuantileFitResult",
    "RiskFactor",
    "RiskResult",
    "ScenarioMetadata",
    "SigmoidImpact",
    "TabulatedDistribution",
    "TransformContext",
    "compute_risk",
    "compute_spanning_set",
    "fit_all",
    "fit_distribution",
    "fit_hurdle_quantiles",
    "fit_quantiles",
    "generate_microscores",
    "impacts",
    "lookup_continent",
    "lookup_geography",
    "lookup_ipcc_region",
    "quality_metrics",
]
